I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/police_cert_event.rpy", line 64, in script
    Officer "Oh I see, I guess you mean a Cle$%^nce 2e#$er."
ValueError: unsupported format character '^' (0x5e) at index 34

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/police_cert_event.rpy", line 64, in script
    Officer "Oh I see, I guess you mean a Cle$%^nce 2e#$er."
  File "E:\renpy-8.2.0-sdk\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "E:\renpy-8.2.0-sdk\renpy\ast.py", line 615, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "E:\renpy-8.2.0-sdk\renpy\exports.py", line 1482, in say
    what = what % tag_quoting_dict
ValueError: unsupported format character '^' (0x5e) at index 34

Windows-10-10.0.22621 AMD64
Ren'Py 8.2.0.24012702
International Serious Game 1.0
Tue Mar  5 23:02:00 2024
