I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/week_one.rpy", line 297, in script
    text "<font color='red'>Time to select course</font>"
Exception: Sayer 'text' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/week_one.rpy", line 297, in script
    text "<font color='red'>Time to select course</font>"
  File "C:\Users\tlx11\Downloads\renpy-8.2.0-sdk\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "C:\Users\tlx11\Downloads\renpy-8.2.0-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\tlx11\Downloads\renpy-8.2.0-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'text' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.2.0.24012702
International Serious Game 1.0
Thu Mar 14 10:08:47 2024
